In [1]:
import numpy as np
import compas_data as compas

_, x_test, _, y_test, _, y_sex_test,\
        _, y_race_test, _ = compas.get_compas_train_test(random_state = 0)
y_sex_test, y_race_test = np.copy(y_sex_test), np.copy(y_race_test)

(5278, 8)
['sex', 'race', 'priors_count', 'age_cat=25 to 45', 'age_cat=Greater than 45', 'age_cat=Less than 25', 'c_charge_degree=F', 'c_charge_degree=M']
sex
race


In [2]:
 u, c = np.unique(x_test[:, 2], return_counts=True)

In [3]:
u, c

(array([-0.71038047, -0.50492586, -0.29947126, -0.09401665,  0.11143796,
         0.31689256,  0.52234717,  0.72780177,  0.93325638,  1.13871099,
         1.34416559,  1.5496202 ,  1.75507481,  1.96052941,  2.16598402,
         2.37143863,  2.57689323,  2.78234784,  2.98780244,  3.19325705,
         3.39871166,  3.60416626,  3.80962087,  4.01507548,  4.22053008,
         4.6314393 ,  4.8368939 ,  5.04234851,  6.68598536]),
 array([323, 218, 108,  74,  53,  48,  36,  38,  25,  21,  15,  20,   9,
         10,   8,   9,   9,   5,   3,   4,   1,   4,   2,   5,   3,   1,
          2,   1,   1]))

In [23]:
_, x_test, _, y_test, _, y_sex_test,\
        _, y_race_test, _ = compas.get_compas_train_test(random_state = 0)
y_sex_test, y_race_test = np.copy(y_sex_test), np.copy(y_race_test)



    # Feature names:
    # (0) 'sex'                          a = 0, 1
    # (1) 'race'                         b = 0, 1
    # (5) 'priors_count'                 c
    # (2) 'age_cat=25 to 45'             d1
    # (3) 'age_cat=Greater than 45'      d2
    # (4) 'age_cat=Less than 25'         d3, d1+d2+d3 = 1
    # (8) 'c_charge_degree=F'            e1
    # (9) 'c_charge_degree=M'            e2, e1+e2 = 1

    # Label name: 'two_year_recid'          # f = 0, 1
n = y_sex_test.shape[0]
u, c = np.unique(x_test[:, 2], return_counts = True)
    # X_test = np.copy(x_test)
    # replace = [ np.mean(u[1:4] * c[1:4])/np.mean(c[1:4]), np.mean(u[4:] * c[4:])/np.mean(c[4:])]
    # for i in range(n):
    #     if X_test[i, 2] < u[4] and X_test[i, 2]>u[0] :
    #         X_test[i, 2] = replace[0]
    #     elif X_test[i, 2] > u[3]:
    #         X_test[i, 2] = replace[1]
    #     else:
    #         X_test[i, 2] = u[0]

    # pcount = [u[0]] + replace
    # pcount = [(v, ) for v in pcount]

    # u = list(u)
    # u = [(v,) for v in u]  

(5278, 8)
['sex', 'race', 'priors_count', 'age_cat=25 to 45', 'age_cat=Greater than 45', 'age_cat=Less than 25', 'c_charge_degree=F', 'c_charge_degree=M']
sex
race


(1056, 7)

In [16]:
space_Z = []
for a in [[0], [1]]:
    pa = tuple(a)
    for b in [[0], [1]]:
        pb = pa + tuple(b)
        for c in u:
            pc = pb + (c, )
            for d in [(1,0,0), (0,1,0), (0,0,1)]:
                pd = pc + d
                for e in [(1,0), (0,1)]:
                    pe = pd + e
                    for f in [[0], [1]]:
                        data_point = pe + tuple(f)
                        space_Z.append(data_point)
K = len(space_Z)
space_Z = np.array(space_Z, dtype='float64')
print(K)
p_n = list(0 for _ in range(K))






1392


In [22]:
indices = []
z_test = np.concatenate((x_test, y_test.reshape((-1, 1))), axis = 1).astype('float64')
for i in range(n):
    z = z_test[i, :]
    lens = [2, 2, np.shape(u)[0], 3, 2, 2]
    lu = np.shape(u)[0]
    ind = z[-1] + np.sum(z[6:8] * np.array([0, 1])) * 2 + np.sum(z[3:6] * np.array([0, 1, 2])) * 2 * 2 + \
        np.where(u == z[2])[0] * 2 * 2 * 3 + z[1] * 2 * 2 * 3 * lu + z[0] * 2 * 2 * 3 * lu * 2
    indices.append(int(ind[0]))
np.unique(indices)

array([   0,    3,    4,    7,    8,   11,   12,   15,   16,   19,   20,
         23,   24,   27,   28,   31,   32,   35,   36,   39,   40,   43,
         44,   47,   48,   51,   55,   56,   59,   60,   63,   64,   71,
         72,   75,   76,   79,   80,   83,   84,   87,   88,   91,   92,
         95,   96,   99,  100,  103,  108,  111,  123,  127,  132,  135,
        136,  143,  144,  147,  148,  151,  159,  163,  171,  175,  180,
        183,  184,  187,  191,  195,  196,  199,  207,  211,  215,  219,
        223,  235,  247,  256,  259,  267,  279,  283,  288,  291,  292,
        303,  315,  327,  348,  351,  352,  355,  356,  359,  360,  363,
        364,  367,  368,  371,  372,  375,  376,  379,  380,  383,  384,
        387,  388,  391,  395,  396,  399,  400,  403,  408,  411,  412,
        415,  419,  420,  423,  427,  435,  444,  448,  451,  452,  455,
        456,  459,  463,  471,  475,  480,  483,  487,  492,  496,  507,
        516,  519,  523,  528,  583,  631,  691,  6

In [13]:
v = (u - u[0])
v = v /v[1]
v

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 26.,
       27., 28., 36.])

In [14]:
t1 = np.sum(u[1:4] * c[1:4])/np.sum(c[1:4])
t2 = np.sum(u[4:] * c[4:])/np.sum(c[4:])
t0 = u[0]
v = [t0, t1, t2]
v

[-0.7103804698258719, -0.37343491539979135, 1.1504336225879908]

In [15]:
pcount = np.copy(x_test[:, 2])
pcount_new = np.zeros((n,))

array([-0.50492586, -0.71038047, -0.71038047, ..., -0.29947126,
        1.34416559,  0.31689256])

In [ ]:
Z_dict = dict(zip([tuple(space_Z[i, :]) for i in range(K)], list(range(K))))
z_test = np.concatenate((x_test, y_test.reshape((-1, 1))), axis = 1).astype('float64')
print(Z_dict)
for i in range(n):
    z = tuple(z_test[i, :])
        #z = tuple(int(x) for x in z)
    p_n[Z_dict.get(z)] += 1

In [24]:
x_test.shape

(1056, 7)

In [29]:
np.mean(x_test[:, 3] + x_test[:, 4] + x_test[:, 5])

1.0